"""
Ko'p tillilik (i18n): o'zbek (uz), rus (ru), ingliz (en).

Foydalanish:
    from i18n import t
    t("welcome", lang, name="Ali")

Agar tarjima topilmasa, "uz" tiliga, keyin kalit nomiga qaytadi.
"""

from __future__ import annotations

import config

# Til nomlari (til tanlash menyusi uchun)
LANG_NAMES: dict[str, str] = {
    "uz": "🇺🇿 O'zbekcha",
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
}

# Gemini promptlarida ishlatish uchun til ko'rsatmalari
LANG_PROMPT: dict[str, str] = {
    "uz": "o'zbek tilida (uzbek language)",
    "ru": "на русском языке (russian language)",
    "en": "in English",
}

TEXTS: dict[str, dict[str, str]] = {
    # --- Til tanlash ---
    "choose_language": {
        "uz": "🌐 Tilni tanlang:",
        "ru": "🌐 Выберите язык:",
        "en": "🌐 Choose your language:",
    },
    "language_set": {
        "uz": "✅ Til o'rnatildi: O'zbekcha",
        "ru": "✅ Язык установлен: Русский",
        "en": "✅ Language set: English",
    },
    # --- Asosiy menyu ---
    "welcome": {
        "uz": (
            "👋 <b>Assalomu alaykum, {name}!</b>\n\n"
            "Men — <b>AI Test Bot</b>. Turli fanlardan testlar yechib, "
            "bilimingizni sinab ko'rishingiz mumkin. Savollarni sun'iy intellekt "
            "(Gemini) generatsiya qiladi va xatolaringizni tushuntiradi.\n\n"
            "Quyidagi bo'limlardan birini tanlang 👇"
        ),
        "ru": (
            "👋 <b>Здравствуйте, {name}!</b>\n\n"
            "Я — <b>AI Test Bot</b>. Решайте тесты по разным предметам и "
            "проверяйте свои знания. Вопросы генерирует искусственный интеллект "
            "(Gemini), он же объясняет ваши ошибки.\n\n"
            "Выберите один из разделов ниже 👇"
        ),
        "en": (
            "👋 <b>Hello, {name}!</b>\n\n"
            "I'm the <b>AI Test Bot</b>. Take quizzes in various subjects and "
            "test your knowledge. Questions are generated by artificial "
            "intelligence (Gemini), which also explains your mistakes.\n\n"
            "Choose one of the sections below 👇"
        ),
    },
    "menu_test": {
        "uz": "📚 Test boshlash",
        "ru": "📚 Начать тест",
        "en": "📚 Start a test",
    },
    "menu_stats": {
        "uz": "📊 Mening natijalarim",
        "ru": "📊 Мои результаты",
        "en": "📊 My results",
    },
    "menu_about": {
        "uz": "ℹ️ Bot haqida",
        "ru": "ℹ️ О боте",
        "en": "ℹ️ About the bot",
    },
    "menu_language": {
        "uz": "🌐 Til / Language",
        "ru": "🌐 Язык / Language",
        "en": "🌐 Language",
    },
    # --- Tugmalar ---
    "btn_back": {
        "uz": "🔙 Orqaga",
        "ru": "🔙 Назад",
        "en": "🔙 Back",
    },
    "btn_home": {
        "uz": "🏠 Asosiy menyu",
        "ru": "🏠 Главное меню",
        "en": "🏠 Main menu",
    },
    "btn_stop_test": {
        "uz": "❌ Testni to'xtatish",
        "ru": "❌ Остановить тест",
        "en": "❌ Stop the test",
    },
    # --- Bot haqida ---
    "about": {
        "uz": (
            "ℹ️ <b>Bot haqida</b>\n\n"
            "Bu bot quyidagi fanlardan testlar tayyorlaydi:\n"
            "🔢 Matematika, 📖 Ona tili, 🏛 Tarix, 🇬🇧 Ingliz tili (IELTS & Grammar), "
            "⚛️ Fizika, 🧬 Biologiya, 🧪 Kimyo, 🌍 Geografiya.\n\n"
            "🧠 <b>AI (Gemini) nima qiladi:</b>\n"
            "• Har bir fan uchun mavzular taklif qiladi\n"
            "• {num} ta A/B/C/D savol generatsiya qiladi\n"
            "• Test yakunida xatolaringizni tushuntiradi\n\n"
            "⚙️ <b>Imkoniyatlar:</b> 3 til, 3 qiyinlik darajasi, har bir savolga {time}s vaqt.\n\n"
            "📊 Natijalaringiz saqlanadi — istalgan vaqtda statistikani ko'rishingiz mumkin."
        ),
        "ru": (
            "ℹ️ <b>О боте</b>\n\n"
            "Этот бот готовит тесты по следующим предметам:\n"
            "🔢 Математика, 📖 Родной язык, 🏛 История, 🇬🇧 Английский (IELTS & Grammar), "
            "⚛️ Физика, 🧬 Биология, 🧪 Химия, 🌍 География.\n\n"
            "🧠 <b>Что делает ИИ (Gemini):</b>\n"
            "• Предлагает темы по каждому предмету\n"
            "• Генерирует {num} вопросов A/B/C/D\n"
            "• Объясняет ваши ошибки в конце теста\n\n"
            "⚙️ <b>Возможности:</b> 3 языка, 3 уровня сложности, {time}с на вопрос.\n\n"
            "📊 Ваши результаты сохраняются — статистику можно посмотреть в любое время."
        ),
        "en": (
            "ℹ️ <b>About the bot</b>\n\n"
            "This bot prepares tests in the following subjects:\n"
            "🔢 Mathematics, 📖 Native language, 🏛 History, 🇬🇧 English (IELTS & Grammar), "
            "⚛️ Physics, 🧬 Biology, 🧪 Chemistry, 🌍 Geography.\n\n"
            "🧠 <b>What the AI (Gemini) does:</b>\n"
            "• Suggests topics for each subject\n"
            "• Generates {num} A/B/C/D questions\n"
            "• Explains your mistakes at the end of the test\n\n"
            "⚙️ <b>Features:</b> 3 languages, 3 difficulty levels, {time}s per question.\n\n"
            "📊 Your results are saved — you can view statistics anytime."
        ),
    },
    # --- Test oqimi ---
    "choose_subject": {
        "uz": "📚 <b>Qaysi fandan test ishlamoqchisiz?</b>",
        "ru": "📚 <b>По какому предмету пройти тест?</b>",
        "en": "📚 <b>Which subject would you like to be tested on?</b>",
    },
    "choose_section": {
        "uz": "{emoji} <b>{subject}</b>\n\nQaysi bo'limdan test ishlaysiz?",
        "ru": "{emoji} <b>{subject}</b>\n\nКакой раздел выбрать?",
        "en": "{emoji} <b>{subject}</b>\n\nWhich section would you like?",
    },
    "choose_difficulty": {
        "uz": "🎯 <b>Qiyinlik darajasini tanlang:</b>",
        "ru": "🎯 <b>Выберите уровень сложности:</b>",
        "en": "🎯 <b>Choose the difficulty level:</b>",
    },
    "loading_topics": {
        "uz": "⏳ Mavzular tayyorlanmoqda...",
        "ru": "⏳ Готовлю темы...",
        "en": "⏳ Preparing topics...",
    },
    "topics_error": {
        "uz": "😔 Mavzularni olishda xatolik yuz berdi. Birozdan so'ng qayta urinib ko'ring.",
        "ru": "😔 Не удалось получить темы. Попробуйте позже.",
        "en": "😔 Failed to load topics. Please try again later.",
    },
    "choose_topic": {
        "uz": "{emoji} <b>{title}</b>\n\n📋 Mavzulardan birini tanlang:",
        "ru": "{emoji} <b>{title}</b>\n\n📋 Выберите одну из тем:",
        "en": "{emoji} <b>{title}</b>\n\n📋 Choose one of the topics:",
    },
    "loading_questions": {
        "uz": (
            "⏳ <b>{topic}</b> mavzusidan {num} ta savol tayyorlanmoqda...\n"
            "Bu bir necha soniya vaqt olishi mumkin."
        ),
        "ru": (
            "⏳ Готовлю {num} вопросов по теме <b>{topic}</b>...\n"
            "Это может занять несколько секунд."
        ),
        "en": (
            "⏳ Preparing {num} questions on <b>{topic}</b>...\n"
            "This may take a few seconds."
        ),
    },
    "questions_error": {
        "uz": "😔 Savollarni tayyorlashda xatolik yuz berdi. Qayta urinib ko'ring.",
        "ru": "😔 Не удалось подготовить вопросы. Попробуйте ещё раз.",
        "en": "😔 Failed to prepare questions. Please try again.",
    },
    "question": {
        "uz": "❓ <b>Savol {n}/{total}</b>   ⏱ {time}s",
        "ru": "❓ <b>Вопрос {n}/{total}</b>   ⏱ {time}с",
        "en": "❓ <b>Question {n}/{total}</b>   ⏱ {time}s",
    },
    "time_up": {
        "uz": "⏰ Vaqt tugadi! Keyingi savolga o'tildi.",
        "ru": "⏰ Время вышло! Переход к следующему вопросу.",
        "en": "⏰ Time's up! Moving to the next question.",
    },
    # --- Natija ---
    "test_finished": {
        "uz": "🏁 <b>Test yakunlandi!</b>",
        "ru": "🏁 <b>Тест завершён!</b>",
        "en": "🏁 <b>Test finished!</b>",
    },
    "result_subject": {
        "uz": "📚 Fan",
        "ru": "📚 Предмет",
        "en": "📚 Subject",
    },
    "result_topic": {
        "uz": "📌 Mavzu",
        "ru": "📌 Тема",
        "en": "📌 Topic",
    },
    "result_difficulty": {
        "uz": "🎯 Daraja",
        "ru": "🎯 Сложность",
        "en": "🎯 Difficulty",
    },
    "result_correct": {
        "uz": "✅ To'g'ri",
        "ru": "✅ Верно",
        "en": "✅ Correct",
    },
    "result_wrong": {
        "uz": "❌ Xato",
        "ru": "❌ Ошибки",
        "en": "❌ Wrong",
    },
    "result_score": {
        "uz": "📊 Natija",
        "ru": "📊 Результат",
        "en": "📊 Score",
    },
    "ai_feedback": {
        "uz": "🧠 <b>AI tavsiyasi:</b>\n",
        "ru": "🧠 <b>Совет от ИИ:</b>\n",
        "en": "🧠 <b>AI feedback:</b>\n",
    },
    "all_correct": {
        "uz": "🎉 Barcha savollarga to'g'ri javob berdingiz! Zo'r natija!",
        "ru": "🎉 Вы ответили правильно на все вопросы! Отличный результат!",
        "en": "🎉 You answered all questions correctly! Great job!",
    },
    "wrong_analysis_title": {
        "uz": "📝 <b>Xatolar tahlili:</b>\n",
        "ru": "📝 <b>Разбор ошибок:</b>\n",
        "en": "📝 <b>Mistake analysis:</b>\n",
    },
    "wrong_q": {
        "uz": "Savol",
        "ru": "Вопрос",
        "en": "Question",
    },
    "your_answer": {
        "uz": "❌ Sizning javobingiz",
        "ru": "❌ Ваш ответ",
        "en": "❌ Your answer",
    },
    "no_answer": {
        "uz": "(javob berilmagan / vaqt tugagan)",
        "ru": "(нет ответа / время вышло)",
        "en": "(no answer / time's up)",
    },
    "correct_answer": {
        "uz": "✅ To'g'ri javob",
        "ru": "✅ Правильный ответ",
        "en": "✅ Correct answer",
    },
    "continue_below": {
        "uz": "Quyidagidan davom eting 👇",
        "ru": "Продолжите ниже 👇",
        "en": "Continue below 👇",
    },
    # --- Grade ---
    "grade_excellent": {"uz": "🏆 A'lo!", "ru": "🏆 Отлично!", "en": "🏆 Excellent!"},
    "grade_good": {"uz": "👍 Yaxshi", "ru": "👍 Хорошо", "en": "👍 Good"},
    "grade_ok": {"uz": "🙂 Qoniqarli", "ru": "🙂 Удовлетворительно", "en": "🙂 Fair"},
    "grade_bad": {
        "uz": "📚 Mashq qilish kerak",
        "ru": "📚 Нужно потренироваться",
        "en": "📚 Needs practice",
    },
    # --- Statistika ---
    "stats_title": {
        "uz": "📊 <b>Mening natijalarim</b>",
        "ru": "📊 <b>Мои результаты</b>",
        "en": "📊 <b>My results</b>",
    },
    "stats_empty": {
        "uz": (
            "📊 <b>Mening natijalarim</b>\n\n"
            "Hozircha test ishlamadingiz. \"📚 Test boshlash\" tugmasini bosing!"
        ),
        "ru": (
            "📊 <b>Мои результаты</b>\n\n"
            "Вы ещё не проходили тесты. Нажмите «📚 Начать тест»!"
        ),
        "en": (
            "📊 <b>My results</b>\n\n"
            "You haven't taken any tests yet. Press \"📚 Start a test\"!"
        ),
    },
    "stats_overall": {
        "uz": "<b>Umumiy statistika:</b>",
        "ru": "<b>Общая статистика:</b>",
        "en": "<b>Overall statistics:</b>",
    },
    "stats_tests": {
        "uz": "Ishlangan testlar",
        "ru": "Пройдено тестов",
        "en": "Tests taken",
    },
    "stats_questions": {
        "uz": "Jami savollar",
        "ru": "Всего вопросов",
        "en": "Total questions",
    },
    "stats_correct": {
        "uz": "To'g'ri javoblar",
        "ru": "Верных ответов",
        "en": "Correct answers",
    },
    "stats_avg": {
        "uz": "O'rtacha natija",
        "ru": "Средний результат",
        "en": "Average score",
    },
    "stats_best": {
        "uz": "Eng yaxshi natija",
        "ru": "Лучший результат",
        "en": "Best score",
    },
    "stats_by_subject": {
        "uz": "<b>Fanlar bo'yicha:</b>",
        "ru": "<b>По предметам:</b>",
        "en": "<b>By subject:</b>",
    },
    "stats_tests_count": {
        "uz": "ta test",
        "ru": "тест(ов)",
        "en": "test(s)",
    },
    "stats_recent": {
        "uz": "<b>So'nggi testlar:</b>",
        "ru": "<b>Последние тесты:</b>",
        "en": "<b>Recent tests:</b>",
    },
}


def t(key: str, lang: str | None = None, **kwargs) -> str:
    """Tarjimani olish va format qilish."""
    lang = lang if lang in config.LANGUAGES else config.DEFAULT_LANGUAGE
    entry = TEXTS.get(key, {})
    text = entry.get(lang) or entry.get("uz") or key
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return text
